name: CI

on:
  push:
    branches: [auto]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Build/Test
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly", "1.56.1"]
        os: [ubuntu-latest]
        include:
          - toolchain: stable
          - toolchain: beta
          - os: windows-latest
            toolchain: nightly

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc libiberty-dev

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test
        if: matrix.toolchain != '1.56.1'
        run: cargo test --verbose
  
      - name: Cargo bench
        if: matrix.toolchain == 'nightly'
        run: cargo run --release --manifest-path=bench/Cargo.toml

      - name: miri
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'
        run: bash ./scripts/run_miri.sh
        env:
          MIRIFLAGS: '-Zmiri-tag-raw-pointers'

  build_result:
    name: build finished
    runs-on: ubuntu-latest
    needs:
      - "ci"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"